kind: Parameterizer
apiVersion: kubernetes.sh/v1alpha1
metadata:
  name: install-kubeless
spec:
  resources:
  - name: kubeless-jsonnet
    source:
      fetch:
        urls:
          - https://raw.githubusercontent.com/kubeless/kubeless/master/kubeless.jsonnet
          - https://raw.githubusercontent.com/kubeless/kubeless/master/kubeless-non-rbac.jsonnet
        dest: /resources
    volumeMounts:
      - name: kubeless-input
        mountPath: /resources

  volumes:
  - name: kubeless-input
    emptyDir: {medium: ""}

  transformations:
  - container:
      name: ksonnet
      image: quay.io/ant31/ksonnet
      command:
        - kubecfg
        - show
        - -o
        - yaml
        - /resources/kubeless.jsonnet
      volumeMounts:
        - name: kubeless-input
          mountPath: /resources
